### ISSUE TITLE
Can you make locale folder?

### ISSUE THREAD

**Issue by rikusen0335** [FriendsOfFlarum/share-social#2]
Title is it

**Comment by datitisev** [comment]
Hello. We do have a locale folder, it is located in the `resources` folder.

However, Friends of Flarum does not accept locales for any languages other than English, so we can focus more on the extension development rather than localization. 

See https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack for a discussion on this matter.
